### ISSUE TITLE
JOSS Reviewer comments:

### ISSUE THREAD

**Issue by AoifeHughes** [shalinshah1993/temporalDNAbarcodes#3]
Ref: [ExTemp Review](https://github.com/openjournals/joss-reviews/issues/2026)

# General comments

- Some minor grammar errors in the paper.pdf, e.g. "`In particular, since the fluorescent signal comes from dye-labeled DNA, hence temporal DNA barcodes`". To me this doesn't read-well
- The text itself seems a little light and hard to understand. I looked at the cited paper in Nano letters and it is explained much better. I raise this as a point in order to make any potential user more aware of what it is this software package does/works with. 
- There are no acknowledgements, I see from your previous work that you are funded by `National Science Foundation Grants` (though, it is mentioned in the readme.MD). 
- I don't find author contributions in the paper (though they are in the readme.MD).
- As you are using MATLAB, can you confirm what packages/toolboxes that a user will need, additionally, it would be useful to highlight which MATLAB versions the software should work on.
- I note you used on a HPC equiment to run your experiments, can you comment on if a 'standard' desktop PC is enough for this, or if HPC access is required to perform analysis in regular time?
- Your readme.MD mentions `they can be used for any arbitrary microscopy project that requires data extraction from fluorescence microscopy data` - perhaps expanding on this and showing some general usecases would be good to make this software useful for a wider audience? 
- Have you tested in Octave, it would be useful to know if FOSS software is capable of running these modules rather than closed platforms.
- Do you provide estimations for expected errors from running your software, is there an alternative form of analysis? When similar experiments were ran prior to 2019, how were their data analysed? 

# Review guidelines to be met: 

- ` If there are any performance claims of the software, have they been confirmed` I cannot easily test this, are you able to provide any automated testing with example data
- The above comment also would address the requirements for: example usage, functionality and automated tests.

**Comment by AoifeHughes** [comment]
I've re-read your readme.MD and I apologise, I missed the note you make about a cluster being required. This makes it difficult as a reviewer to confirm that the software runs and produces expected and valid outputs. Would you have suggestions of any easy methods to verify results?

**Comment by shalinshah1993** [comment]
Thank you for the detailed review @SirSharpest 

1. Done. Please check the paper. ` In particular, the fluorescent signal comes from a dye-labeled fluorescent DNA...`

2. Thank you! Yes, a lot of package details are also in the supplementary of the paper.

3. I've added them to the papers as well. Thanks for pointing this out! 

4. I've added the author contributions to the paper as well. Thanks for pointing this out! 

5. Thanks for pointing this out. We need Statistics and machine learning toolbox. I've added this in the dependencies section of README.md along with external dependencies. The version of MATLAB I used can be found in the system section however I believe it should work for anything >= 2018

6. Yes, we used an HPC system however you don't need it, in principle, to test. For example, if you run `lif2mat 'sample_data.lif'` it should convert proprietary Leica file to Matlab `.m` file as long as sample data is relatively small in size (a few hundred MBs). We require HPC since most large-scale microscopy experiments have raw data of several tens or hundreds of gigabytes.  (Refer to the end of this post to download the sample file from duke box)

7. We have not used or tested it in Octave. Unfortunately, it will be difficult at this point to have a dedicated person working on the Octave version of ExTemp. However, this will certainly be an exciting future alternative. 

8. Maybe the supplementary section of the published paper can help? If so, we can cite it somewhere in the README. https://pubs.acs.org/doi/suppl/10.1021/acs.nanolett.9b00590/suppl_file/nl9b00590_si_001.pdf 

Also, here is how I recommend you do an auto-test of the `sample_data.lif` (after downloading it from duke box https://duke.box.com/s/9xy67550rdawj6pk4woqxnyhwknq0n3c):

lif2mat('sample_data.lif')

This will process the lif file and produce Matlab .m file in /tmp/mat/ folder. Refer to README file https://github.com/shalinshah1993/temporalDNAbarcodes#module-description-sample-use to similarly try other portions of the package if you desire.

**Comment by shalinshah1993** [comment]
@SirSharpest if all your concerns are addressed, please close this issue. Thank you for your time and efforts with review :)
